# File/Directory Paths
data_path: ./data
chroma_path: ./chroma_db
snapshot_path: ./snapshots

# Chunking Params
chunk:
  size: 800
  overlap: 80

# Embedding Model
embedding:
  model_name: all-MiniLM-L6-v2

# Local LLM
llm:
  local_model_path: ./models/mistral.gguf
  temperature: 0.7
  top_p: 0.95
  max_tokens: 512
  n_ctx: 2048
  n_threads: 4
